### ISSUE TITLE
NoClassDefFoundError on Android Build

### ISSUE THREAD

**Issue by Ridwansameer** [Scandit/barcodescanner-sdk-react-native#174]
Trying to import the BarcodeScanner after updating to RN 0.59 produces the follow error on an Android Build and the app crashes

`08-09 18:13:37.055 4923-4969/com.scandit.extendedsample E/AndroidRuntime: FATAL EXCEPTION: engine thread
                                                                          Process: com.scandit.extendedsample, PID: 4923
                                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microblink/view/recognition/ScanResultListener;
                                                                              at com.scandit.barcodepicker.internal.EngineThread.getInstance(EngineThread.java:144)
                                                                              at com.scandit.barcodepicker.internal.BarcodePickerInternal.<init>(BarcodePickerInternal.java:271)
                                                                              at com.scandit.barcodepicker.BarcodePicker.<init>(BarcodePicker.java:73)
                                                                              at com.scandit.reactnative.BarcodePicker.createViewInstance(BarcodePicker.kt:114)
                                                                              at com.scandit.reactnative.BarcodePicker.createViewInstance(BarcodePicker.kt:27)
                                                                              at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
                                                                              at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:256)
                                                                              at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
                                                                              at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)
                                                                              at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)
                                                                              at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                                              at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
                                                                              at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:693)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                                                                              at android.os.Handler.handleCallback(Handler.java:873)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:193)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.microblink.view.recognition.ScanResultListener" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.scandit.extendedsample-pSSx9cOc9z1kxb3IL5SIUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.scandit.extendedsample-pSSx9cOc9z1kxb3IL5SIUw==/lib/x86, /data/app/com.scandit.extendedsample-pSSx9cOc9z1kxb3IL5SIUw==/base.apk!/lib/x86, /system/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

The project was recently upgraded to RN 0.59 and the SDK was upgraded to 5.11.3

The same issues also occurs using the ExtendedSample app from the samples provided, It seems to be incompatible with RN 0.59

**Comment by moritzhartmeier** [comment]
Hi @Ridwansameer 

The stack trace looks like you have downloaded the OCR version of our SDK and it doesn't find the second aar required for OCR. Our ReactNative plugin does currently not support OCR and therefore doesn't try to load this second aar, which leads to it not being available here. If you download non-OCR build of the native Android library this should not be happening, could you try this?

**Comment by Ridwansameer** [comment]
That might be it. Will revert back on Monday if it works.

Is the SDK you're referring to titled "Barcode Scanner SDK for Android, Phonegap"  & "Barcode Scanner SDK for iOS, Phonegap"?

That was pretty far down on the Downloads section, so wasn't aware we should be using it.

Thanks for the prompt reply :)

**Comment by Ridwansameer** [comment]
That seems to have fixed the issue. The SDK with OCR works for iOS but not Android.

Thank you!
