### ISSUE TITLE
Samples not working because of microQR

### ISSUE THREAD

**Issue by bjo-rs** [Scandit/barcodescanner-sdk-react-native#44]
I'm trying to run the sample applications but have problems with both Simple and Extended apps, both seemingly related to microQR. 

Simple app crashes with a react-native error complaining about microQR. I remove the microQR setSymbologyEnabled line and then I can run that app. 
The Extended app is the one I really need to look at. This one crashes outside react native as soon as I start it up with the following error: 

```
FATAL EXCEPTION: main
                                                                            Process: com.scandit.extendedsample, PID: 31608
                                                                            java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
                                                                             Caused by: com.scandit.base.util.JSONParseException: unknown symbology 'microQR'
                                                                                at com.scandit.recognition.BarcodeScannerSettings.settingsFromJson(BarcodeScannerSettings.java:256)
                                                                                at com.scandit.recognition.BarcodeScannerSettings.<init>(BarcodeScannerSettings.java:243)
                                                                                at com.scandit.recognition.BarcodeScannerSettings.createWithJson(BarcodeScannerSettings.java:191)
                                                                                at com.scandit.barcodepicker.ScanSettings.<init>(ScanSettings.java:492)
                                                                                at com.scandit.barcodepicker.ScanSettings.createWithJson(ScanSettings.java:583)
                                                                                at com.scandit.reactnative.BridgeHelpersKt.settingsFromMap(BridgeHelpers.kt:180)
                                                                                at com.scandit.reactnative.BarcodePicker.setScanSettings(BarcodePicker.kt:202)
                                                                                at com.scandit.reactnative.BarcodePicker.receiveCommand(BarcodePicker.kt:65)
                                                                                at com.scandit.reactnative.BarcodePicker.receiveCommand(BarcodePicker.kt:21)
                                                                                at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:715)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:262)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
                                                                                at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                                at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                                                at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:957)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
```

Again, microQR. What am I missing? I'm using the latest Scandit SDK, 2.6.1.

**Comment by moritzhartmeier** [comment]
Please use the release-5.6 branch, master is the one under development for the 5.7 release for which the native library is not available yet. We are aware that this is a bit confusing and will change the github around a bit soon to make sure that people are using the correct production version.

**Comment by bjo-rs** [comment]
Ah, that makes a lot of sense! Didn't see the 5.6 release branch since I was looking for tags. 

Thanks!
