### ISSUE TITLE
Error: Cannot find module '...react-native-scandit/package.json'

### ISSUE THREAD

**Issue by zabojad** [Scandit/barcodescanner-sdk-react-native#68]
First install steps from the documentation and I'm getting:
```
$ npm install react-native-scandit@https://github.com/Scandit/barcodescanner-sdk-react-native.git --save
ShifteoPOS@0.0.1 /Users/thomasfetiveau/wksp_myproj/myproj/bin
└── scandit-react-native@5.9.0-SNAPSHOT  (git+https://github.com/Scandit/barcodescanner-sdk-react-native.git#2441cffa5873f35805e4c06db11abb982666b4eb)
$ react-native link react-native-scandit
Scanning folders for symlinks in /Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules (10ms)
{ Error: Cannot find module '/Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules/react-native-scandit/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getRNPMConfig (/Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules/react-native/local-cli/core/index.js:55:3)
    at Object.getDependencyConfig (/Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules/react-native/local-cli/core/index.js:117:18)
    at deps.reduce.err (/Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules/react-native/local-cli/link/getDependencyConfig.js:18:24)
    at Array.reduce (native)
    at getDependencyConfig (/Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules/react-native/local-cli/link/getDependencyConfig.js:15:15)
    at Object.link (/Users/thomasfetiveau/wksp_myproj/myproj/bin/node_modules/react-native/local-cli/link/link.js:133:24) code: 'MODULE_NOT_FOUND' }
```

What's wrong doc?

**Comment by robertnawrot** [comment]
Hey @zabojad 
Actually we're on NPM now so you don't need the github link :)
Also, I'd advise using yarn in place of npm because for some reasons npm doesn't like our sample apps
Also also, we changed the module's name to scandit-react-native
So use `yarn install scandit-react-native` and you should be golden
I promise we'll update the docs soon :)

Pozdrawiam, 
Robert ze Scandit

**Comment by zabojad** [comment]
Hehe, czesc @robertnawrot !

Thanks for your reply, it indeed works now, even using npm, with the `scandit-react-native`.

By the way, great work done on the library, it's really fast at scanning bar codes...

Pozdrawiam serdeczne rowniez...
Thomas ze Shifteo.
