### ISSUE TITLE
Extended Example not starting on Android, since code32 is unknown symbology

### ISSUE THREAD

**Issue by abrass** [Scandit/barcodescanner-sdk-react-native#79]
SimpleExample works fine, but I cannot start the ExtendedSample on Android with following error.

Seems that a piece of code is missing, which is connected to code32:

Process: com.scandit.extendedsample, PID: 19409
                                                                            java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                                             Caused by: com.scandit.base.util.JSONParseException: unknown symbology 'code32'
                                                                                at com.scandit.recognition.BarcodeScannerSettings.settingsFromJson(BarcodeScannerSettings.java:256)
                                                                                at com.scandit.recognition.BarcodeScannerSettings.<init>(BarcodeScannerSettings.java:243)
                                                                                at com.scandit.recognition.BarcodeScannerSettings.createWithJson(BarcodeScannerSettings.java:191)
                                                                                at com.scandit.barcodepicker.ScanSettings.<init>(ScanSettings.java:495)
                                                                                at com.scandit.barcodepicker.ScanSettings.createWithJson(ScanSettings.java:595)
                                                                                at com.scandit.reactnative.BridgeHelpersKt.settingsFromMap(BridgeHelpers.kt:180)
                                                                                at com.scandit.reactnative.BarcodePicker.setScanSettings(BarcodePicker.kt:243)
                                                                                at com.scandit.reactnative.BarcodePicker.receiveCommand(BarcodePicker.kt:67)
                                                                                at com.scandit.reactnative.BarcodePicker.receiveCommand(BarcodePicker.kt:22)
                                                                                at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:715)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:262)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:822)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
                                                                                at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:887)
                                                                                at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
                                                                                at android.os.Handler.handleCallback(Handler.java:790)

**Comment by lucatorella** [comment]
code32 will be added in 5.9 which we didn't release yet. If you use the 5.8 branch, instead of master, you should be able to run the extended sample.

**Comment by abrass** [comment]
ah thanks, i have a try

**Comment by abrass** [comment]
it worked on Android, thx. Maybe a reference in the Readme.MD to the corresponding SDK version might help. Or keep the master as stable and work with branch 5.9-SNAPSHOT

**Comment by lucatorella** [comment]
Yes, we are aware it can be confusing. We are thinking how to improve it :)
